### ISSUE TITLE
Feature Request: Warning banner for data entry pages

### ISSUE THREAD

**Issue by steentje34** [jangari/redcap_warning_banner#1]
At the moment, the module is aimed at trying to prevent survey respondents from entering real data in development & practice/just for fun projects, but apart from changing the color of the warning on the Add/Edit Records page from yellow to red, it does not warn logged in users not to enter any real data.

It would be wonderful if the option could be added to configure a warning banner on all data entry pages (potentially even all project pages). You could for example add this banner after the div-element with the id 'subheader', that seems to be present on all project pages.

Adding this option could help reduce the number of incidents where a user requests to move their project to production and starts entering real data before an administrator can perform the necessary checks and approve the request to move the project to production.

Would you consider adding such an option?

**Comment by jangari** [comment]
Thanks for the suggestion @steentje34, I think that sounds totally reasonable. I'll have a think about whether this should be the standard behaviour (easier to implement), or if it should be controlled by a new EM setting. I'll also consider abstracting out the function that generates the warning div from the hook function so it can be reused better. This all means I'm unlikely to get to it very soon I'm afraid.

**Comment by steentje34** [comment]
@jangari Would it help you if I tried to implement this feature myself and open a pull request once I'm done?

**Comment by jangari** [comment]
@steentje34 Sorry for late response. There has now been another request for this functionality. I think I would be hard pressed to fit it in. If you are still willing to work on it and submit a PR, I would welcome it!

For a data entry form page, it would be best if it were placed as close to the data entry as possible, say, as the first child of the `dataEntryTopOptions` div. That way it should be present even when other EMs (like instance table) remove all other elements apart from the data entry itself. Here's a mockup:

<img width="949" alt="image" src="https://github.com/jangari/redcap_warning_banner/assets/1875291/5f993008-a222-4b89-82b0-a11c78508f3c">

I think in the first instance, including this in the default behaviour would work, and later it can be controlled by a config option. What do you think?

**Comment by jangari** [comment]
@steentje34 I have done this in a quick and inefficient way (see b8370a6). Are you able to test this out?

**Comment by steentje34** [comment]
@jangari Thanks for the new version! We have thoroughly tested it, and are very happy with the result! Thanks!
